apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: cm9vdA==
  password: c2VjcmV0

# echo -n 'root' | base64
# echo -n 'secret' | base64

# kubectl apply -f mysql-secret.yaml