apiVersion: apps/v1          # Kubernetes API version
kind: Deployment            # Kubernetes resource kind we are creating
metadata:
  name: angular-deployment  
spec:
  selector:
    matchLabels:
      app: angular
  replicas: 5               # Number of replicas for this deployment
  template:
    metadata:            
      labels:
        app: angular
    spec:                
      containers:
      - name: angular
        image: tss-docker:1.3 # Image used for containers in the cluster
        ports:          
        - containerPort: 80 # Port the container is running on


---


kind: Service                # Kubernetes resource kind we are creating
apiVersion: v1              # Kubernetes API version
metadata:
  name: angular-service
spec:
  selector:
    app: angular
  ports:            
  - protocol: TCP
    port: 80             # Port the service is running on
    targetPort: 80       # Port exposed by the service
    nodePort: 31000      
  type: NodePort             # Type of the service